default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgresssss

development:
  <<: *default
  database: hello_rails_back_end_development
  host: localhost
  username: postgres
  password: 'Goodmorning123.'

test:
  <<: *default
  database: hello_rails_back_end_test
  username: postgres
  password: 'Goodmorning123.'

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
